name: Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-x86_64:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      name: "libhelium"
      buildVariant: x86_64
  sign-x86_64:
    needs:
      - build-x86_64
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      name: "libhelium"
      buildVariant: x86_64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  upload-x86_64:
    needs:
      - sign-x86_64
    uses: tau-OS/github-actions/.github/workflows/upload-rpm.yml@main
    with:
      name: "libhelium"
      tauOSVersion: "1"
      buildVariant: x86_64
    secrets:
      repoIP: ${{ secrets.REPO_IP }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}

  build-aarch64:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      name: "libhelium"
      buildVariant: aarch64
      runsOn: ARM64
  sign-aarch64:
    needs:
      - build-aarch64
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      name: "libhelium"
      buildVariant: aarch64
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  upload-aarch64:
    needs:
      - sign-aarch64
    uses: tau-OS/github-actions/.github/workflows/upload-rpm.yml@main
    with:
      name: "libhelium"
      tauOSVersion: "1"
      buildVariant: aarch64
    secrets:
      repoIP: ${{ secrets.REPO_IP }}
      repoKnownHosts: ${{ secrets.REPO_KNOWN_HOSTS }}
      repoPrivateKey: ${{ secrets.REPO_PRIVATE_KEY }}
